#!/bin/sh

HEART_FULL=♥
HEART_EMPTY=♡
[ -z "$NUM_HEARTS" ] &&
    NUM_HEARTS=5

cutinate()
{
    perc=$1
    inc=$(( 100 / $NUM_HEARTS))

    for i in `seq $NUM_HEARTS`; do
        if [ $perc -ge 0 ]; then
            echo $HEART_FULL
        else
            echo $HEART_EMPTY
        fi
        perc=$(( $perc - $inc ))
    done
}

# Do with grep and awk unless too hard
battery_status()
{
    case $1 in
        "Discharging")
            ext="No";;
        "Charging")
            ext="Yes";;
    esac

    ioreg -c AppleSmartBattery -w0 | \
    grep -o '"[^"]*" = [^ ]*' | \
    sed -e 's/= //g' -e 's/"//g' | \
    sort | \
    while read key value; do
        case $key in
            "MaxCapacity")
                export maxcap=$value;;
            "CurrentCapacity")
                export curcap=$value;;
            "ExternalConnected")
                if [ "$ext" != "$value" ]; then
                    exit
                fi
            ;;
            "FullyCharged") if [ "$value" = "Yes" ]; then
                    exit
                fi
            ;;
        esac
        if [[ -n "$maxcap" && -n $curcap ]]; then
            echo "100 * $curcap / $maxcap" | bc
            break
        fi
    done
}

BATTERY_STATUS=`battery_status $1`
[ -z "$BATTERY_STATUS" ] && exit

if [ -n "$CUTE_BATTERY_INDICATOR" ]; then
    echo `cutinate $BATTERY_STATUS` ${BATTERY_STATUS}%
else
    echo ${BATTERY_STATUS}%
fi
